version: "3.9"
services:
  database:
    image: database
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd.txt
    networks:
      - backend
    ports:
      - 5432:5432
  cache:
    image: redis:7.2.1-alpine
    networks:
      - backend
    ports:
      - 6379:6379
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass foobarbaz'
networks:
  frontend:
  backend:
