version: "3.9"
services:
  database:
    image: database
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd.txt
    networks:
      - backend
    ports:
      - 5432:5432
networks:
  frontend:
  backend:
