version: "3.9"
services:
  server:
    container_name: server
    build:
      context: ./node
    image: server
    environment:
      - DATABASE_URL_FILE=/run/secrets/postgres-url.txt
      - CACHE_URL_FILE=/run/secrets/redis-url.txt
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    depends_on:
      - database
      - cache
    links:
      - database
      - cache
  database:
    container_name: database
    build:
      context: ./postgres
    image: database
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd.txt
    ports:
      - 5432:5432
    networks:
      - backend
  cache:
    container_name: cache
    image: redis:7.2.1-alpine
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass foobarbaz'
    ports:
      - 6379:6379
    networks:
      - backend
networks:
  frontend:
  backend:
